export const areaOptions = [
    'Consumibles',
    'Alimentacion',
    'Hardlines',
    'Entretenimiento',
    'Mascotas',
    'Casa',
    'Vestuario',
    'Mundo Bebe',
    'Fiambreria y Deli',
    'Panaderia y Pasteleria',
    'Mercaderia Impulsiva',
    'Frutas y Verduras',
    'Carnes y Pescados',
    'Negocio',
    'Restaurante',
    'Financial Services'
];

export const departamentoOptions = [
    'Confiteria',
    'Cuidado e Higiene Corporal',
    'Libreria/Papeleria',
    'Papeles Domesticos',
    'Electronica',
    'Fotografia',
    'Juguetes',
    'Mascotas',
    'Deportes',
    'Automotriz',
    'Ferreteria',
    'Pinturas',
    'Quimicos/Articulos de Limpieza',
    'Articulos Hogar/Organizacion',
    'Electrodomesticos',
    'Jardineria',
    'Muebles/Decoracion/Maleteria',
    'Articulos de Temporada',
    'Telas/Manualidades',
    'Cocina Y Baño',
    'Cortinas Y Persianas',
    'Ropa De Cama',
    'Caballeros',
    'Niños',
    'Zapateria',
    'Consumible Bebe',
    'Calcetines',
    'Panty Medias',
    'Ropa De Dormir',
    'Ropa Interior',
    'Accesorios',
    'Joyeria',
    'Niñas',
    'Damas',
    'Maternidad Y Tallas Grandes',
    'Ventas Descontadas',
    'Snack Bar/Cafeteria',
    'Cuidado Y Salud',
    'Cosmeticos',
    'Optica',
    'Descartables Y Cumpleaños',
    'Vivero/Plantas Vivas',
    'Warranties',
    'Cosmeticos',
    'Deposito De Botellas',
    'Home Delivery',
    'Libros Y Revistas',
    'Vestuario Bebe',
    'Linea Blanca Hogar',
    'Hardlines Bebe',
    'Service Deli',
    'Panaderia/Reposteria Empacada',
    'Check-Outs',
    'Pescado/Marisco Fresco/Conge',
    'Flores/Bouquet',
    'Financial Services',
    'Telefono Movil',
    'Ventas Sustentables',
    'Lacteos',
    'Alimentos Congelados',
    'Abarrotes',
    'Carne Cruda/Congelada',
    'Frutas/Verduras/Granos',
    'Abarrotes/Entrega Directa',
    'Licores',
    'Almuerzo De Carne',
    'Panaderia',
    'Sumistros Para Consumo Interno'
]

export const categoriaOptions = [
    "Acondicionador",
    "Coloracion",
    "Shampoo",
    "Cepillos",
    "Oral - Enjuague",
    "Afeitado Hombre",
    "Afeitado Mujer",
    "Depilacion - Quimica - Cera",
    "Desodorante-Antitranspirante",
    "Estilismo - Productos",
    "Higiene Femenina - Proteccion",
    "Incontinencia Adulto",
    "Estilismo - Herramientas",
    "Estilismo - Accesorios",
    "Bolsa De Basura",
    "Bolsos & Envoltorios",
    "Papel Higiénico",
    "Papeles Facial",
    "Servilletas",
    "Toallas De Papel",
    "Primeros Auxilios",
    "Fragancia & Perfumes",
    "Candy - Chocolates",
    "Candy - Duro- Blando",
    "Tabaco & Fumar",
    "Carpetas & Archivos",
    "Artesania - Arte Infantil",
    "Papel", "Instrumentos Escritura",
    "Vehiculos - Colecciones-Modelo",
    "Juegos Aire Libre",
    "Figuras Accion & Coleccionable",
    "Peluches",
    "Comida Gato", "Comida Perro", "Juguetes-Accesorios", "Otras Comidas", "Limpiadores - Hogar", "Fosforos", "Articulos De Limpieza - Guantes", "Acc Alim-Horn-Cocina", "Alim-Horn-Cocina", "Almacen-Organiza", "Vajilla", "Conservacion Alim", "Lavand-Organiza Closet", "Cocina Outdoor", "Sala De Estar", "Celebraciones - Semana Santa", "Celebraciones - Navidad", "Celebraciones - Eventos Nacionales", "Velas - Esencias", "Textil-Cocina-Comedor", "Decoracion Baño", "Cama Almohada-Cojines", "Caballero - Polera Sport", "Caballero - Traje De Baño", "Calzado - Cuidado", "Calzado - Hombres", "Calzado Niña", "Calzado Mujer", "Pañales Bebe-Entrena", "Cuidado Bebe", "Alimentos Bebe", "Formulas Bebe", "Acces Dormir", "Juguetes Y Actividades", "Pijamas", "Zapatos Bebe", "Puericultura", "Bebe - Ropa Casual", "Medias", "Bols Mano-Carteras", "Niña - Ropa Casual", "Quesos", "Pan  - Gondola", "Revistas Y Periódicos", "Pilas", "Pescaderia-Otros", "Pescaderia-Pescado", "Telefono & Comunicaciones", "Yogurt", "Mantequilla-Manteca", "Cremas", "Postres", "Entrada-Prepar&Cong", "Helados Y Postres Congelados", "Comida Completa-Prep-Congel", "Prefor & Cortes Frios", "Verduras Congeladas", "Panad-Cocina-Mezclas", "Legumbres", "Bebidas - Cafe", "Bebidas - Te", "Mariscos - Pescado", "Chips-Crips-Mezcla Snacks", "Galletas - Gondola", "Galletas - Salada-Salvia", "Postre-Cubierta Llenado Base", "Harina", "Abarrotes - Frutas Secas", "Frutas - Gondola", "Leche-Crema-Substitutos", "Dulce & Preservantes", "Pasta", "Arroz", "Salsas Y Marinados", "Abarrotes - Mariscos - Pescado", "Abarrotes - Mariscos - Mariscos", "Aderezo-Especia-Hierba-Extracto", "Semillas", "Pure", "Sopas -  Gondola", "Azucar - Sustituto", "Dieta Y Salud", "Verduras - Gondola", "Vinagres- Sucedaneos", "Carne Vacuno - Fresco", "Aves De Corral - Fresca", "Carnes - Otros", "Bebidas - Gas", "Bebidas Diluibles", "Bebidas - Hidratación - Energía", "Bebidas - Jugos", "Bebidas - Agua", "Vino", "Almuerzo De Carne - Cecinas", "Almuerzo De Carne - Quesos", "Huevos", "Masas", "Tartas-Past-En Local", "Pan - En Local", "Tortas - En Local", "Mantencion Local", "Cuidado Pies", "Maternidad-Grandes - Sweaters", "Almacenamiento", "Videos", "Suplemento", "Pizza", "Juegos De Tablero", "Muñecas", "Niña - Traje De Baño", "Caballero - Chaqueta Sport", "Accesorios", "Decoracion Bebe", "Seguridad Del Bebe", "Bebe - Traje De Baño", "Bebe - Ropa Interior", "Dormitorio", "Mochilas-Bolsos", "Decor Hogar - Muralla", "Toallas Playa", "Cama Accesorios", "Cama Sabanas", "Role Play", "Vehiculos - Radio Control", "Electronica Nino Nina", "Cuadernos", "Automotriz - Herramientas - Poder & Acceso", "Electricos", "Iluminacion - Portable", "Buzones - Signos - Numeros", "Fontaneria", "Almacenamiento - Organizacion", "Herramientas - Mano", "Ventilacion", "Cerdo - Fresco", "Comida Preparada", "Procesos Emporium", "Vitaminas", "Equip Medico Y Accesor", "Cuidado Ojos", "Nutricion", "Cuidado Labios", "Floral - Accesorios", "Decor Hogar - Espacios", "Cecinas", "Cama Colchas-Plumones", "Caballero - Denim", "Specialty", "Checkouts - Bebidas - Jugos", "Checkouts - Bebidas - Agua", "Alimentos Internacionales", "Mascotas - Cuidado - Higiene", "Baño & Spa", "Oral  - Accesorios", "Jabon", "Pastas", "Ambientador & Desodorante", "Blanqueamiento", "Limpiadores - Piso", "Detergentes", "Cuidado Telas", "Suavizantes", "Plaguicidas", "Otc - Incontinencia Adulto", "Dieta", "Planificacion Familiar", "Cosmeticos - Baño & Spa", "Cuidado Corporal", "Cuidado Facial", "Cuidado Solar", "Depositos De Botella", "Cara", "Recipientes Limpieza", "Herramientas", "Labios", "Ojos", "Uñas", "Cocina", "Equipaje", "Frutas Congeladas", "Mesas", "Niños", "Oficina", "Dressing", "Aceites", "Cerveza", "Licores", "Mezclas", "Desayuno-Cereal-Barra", "Caballero - Accesorios", "Calcetin Hombre", "Comedor", "Caballero - Casual Juvenil", "Caballero - Casual Sport", "Caballero - Chaqueta Juvenil", "Caballero - Polera Juvenil", "Caballero - Ropa Deportiva", "Ropa Interior Hombre", "Caballero - Sweater Juvenil", "Caballero - Sweater Sport", "Caballero - Vestir", "Accesorios", "Niño - Calcetines", "Outwear", "Bottom", "Polerones Y Sweaters", "Top", "Ropa Interior Niño", "Niño - Traje De Baño", "Niño - Unif Escolares", "Albumes", "Maternidad-Grandes - Ropa Casual", "Maternidad-Grandes - Poleras", "Maternidad-Grandes - Vestidos", "Artesania - Papel", "Colas Pegamentos & Sellantes", "Libreria - Maquina Oficina", "Planificadores & Calendarios", "Audio - Suministros Video", "Accesorios Y Tecnologia", "Computadores - Hardware", "Computadores - Impresora", "Computadores - Software", "Equipos De Audio", "Instrumentos Musicales", "Smart Home", "Electronica - Maquina Oficina", "Musicas", "Televisores", "Video Juegos - Hardware & Acc", "Flores Artificiales", "Decor Hogar - Relojes", "Alfombras", "Toallas Baño", "Camaras - Foto", "Oficina & Suministro Colegio", "Cortinas Baño", "Cortinas Casa", "Cama Cubre Colchon", "Cama Frazadas", "Set Cama", "Suministro Fiestas", "Calzado Niño", "Viajes Bebe", "Muebles Para Bebe", "Denim Bebe", "Libros", "Papel De Regalo", "Set De Regalo", "Tarjetas De Felicitaciones", "Dama - Calcetines", "Jardin - Arboles", "Jardin Flores", "Jardin-Macet & Plantas", "Lenceria - Maternidad", "Ropa Dormir", "Ropa In- Bottoms", "Dulce", "Encurtidos", "Pescaderia-Marisco", "Bufandas", "Cinturon", "Floral - Fresco", "Accesorios - Deportes", "Guante", "Impermeables", "Ropa Int - Tops", "Sostenes", "Sombreros", "Joyas - Relojes", "Joyeria-Bisuteria", "Joyeria-Regalos", "Lentes Sol-Lentes Lect", "Espirituosos", "Almuerzo De Carne - Encurtidos", "Jugos", "Galletas - En Local", "Accesorios Automovil", "Accesorios Interior Automovil", "Servicio Ingresos", "Aceite Motor & Lubricantes", "Automotriz - Ambientador & Desodorante", "Apariencia Automovil", "Fluido Automovil & Quimicos", "Partes Automovil", "Cuidado Personal - Aplicacione", "Proteccion Ext", "Electrodomesticos - Vacio-Limp", "Pequeños", "Electrodomesticos - Grandes", "Maquinas De Coser", "Art Adhesivos", "Calefaccion", "Aparatos De Cuidado Personal", "Velas", "Checkouts - Bebidas - Hidratación&Energía", "Cerraduras & Seguridad", "Checkouts - Bebidas - Gas", "Sujetadores", "Herramientas - Poder & Acceso", "Herramientas - Trabajo Ropa", "Candy - Cajas", "Iluminacion", "Checkouts - Colas Pegamentos & Sellantes", "Incendio - Seguridad Hogar", "Ampolletas", "Como Visto En Tv", "Puerta & Ventana Hardware", "Suministro Poder & Convertidor", "Checkouts - Helados Y Postres Congelados", "Tratamiento Agua", "Acondicionamiento Invierno", "Checkouts - Oficina & Suministro Colegio", "Aplicadores Y Accesorios", "Escalas & Taburetes", "Papel Muralla & Accesorios", "Pintura - Exterior", "Pintura - Interior", "Camaras - Video", "Checkouts - Set De Regalo", "Snacks - Cajas", "Foto Accesorios", "Souvenir & Recuerdos", "Ciencia & Descubrimiento", "Jardin - Fertilizante & Alimen", "Construccion Y Bloques", "Jardin - Herramientas Manuales", "Jardin - Semillas & Bulbos", "Vestuario & Disfraz", "Jardin Diseño", "Maceteros", "Plaguicidas Jardineria", "Bicicletas & Accesorios", "Instrumentos Musicales", "Camping & Excursiones", "Rodados", "Puzzles", "Deportes - Acuatico & Pesca", "Piscina", "Terraza Y Playa", "Deportes - Aerobicos & Fitness", "Gps", "Deportes - Agua", "Telefono Movil - Otros", "Preefectivo", "Deportes - Balones", "Deportes - Bat & Club & Mazo", "Deportes - Combate", "Deportes - Invierno", "Deportes - Raqueta", "Celebraciones - Eventos Global", "Celebraciones - Halloween", "Celebraciones - San Valentin", "Deportes - Skate", "Juegos Mesa - Indoor", "Piscina & Juegos Agua", "Pinturas - Colas Pegamentos & Sellantes", "Cadena Cable & Cuerdas", "Snack Bar - Comidas", "Snack Bar - Heladeria", "Snack Bar - Liquidos", "Juegos Azar", "Almuerzo De Carne - Prefor & Cortes Frios", "Sandw-Pizzas", "Vehiculos - Fricción", "Niña - Unif Escolares", "Niña - Sweaters", "Ropa Interior Niña", "Niña - Calcetines", "Outwear", "Bottom", "Niña - Medias", "Polerones Y Sweaters", "Top", "Dama - Polera Juvenil", "Vestidos", "Dama - Casual", "Dama - Denim", "Dama - Juvenil Casual", "Dama - Polera", "Dama - Poleron", "Dama - Polar Juvenil", "Dama - Ropa Deportiva", "Dama - Sweater", "Dama - Sweater Juvenil", "Dama - Teena", "Dama - Traje De Baño", "Dama - Vestido", "Dama - Vestido Juvenil", "Cocktail", "Sales Discount", "Despacho Domicilio", "Financial Services", "Impresion Digital", "Consignado Afecto", "Consignado Exento", "Consignado Afecto", "Consignado Exento", "Consignado Afecto", "Consignado Exento", "Consignado Afecto", "Consignado Exento", "Consignado Afecto", "Com Preparadas", "Activacion Cajas", "Activacion Cajas", "Productos Industriales", "Funcional", "Polar", "Dulce", "Otros", "Queso Fresco", "Cvp", "Cvp", "Cvp", "Cvp", "Cvp", "Cvp", "Cvp", "Cvp", "Cvp", "Transferencia De Dinero", "Cvp", "Cvp", "Cvp", "Cvp", "Cvp", "Cvp", "Cvp", "Cvp", "Cvp", "Cvp", "Frutas 1", "Frutas 2", "Frutas 3", "Verduras 1", "Verduras 2", "Cervezas Sin Alcohol", "Celebraciones - Ano Nuevo", "Transferencia Dinero", "Maquillaje Infantil", "Verduras 3", "Canastas Fiestas", "Lentes De Sol", "Marcos", "Cristales", "Accesorios", "Lentes De Lectura", "Lentes De Contacto", "Ventilacion", "Calefaccion", "Maletas Y Bolsos", "Terraza", "Mochilas -Loncheras Y Estuches", "Mantencion Local", "Accesorios Bebe", "Decoracion Bebe", "Ropa Casual", "Denim", "Zapatos", "Pijamas", "Traje De Bano", "Ropa Interior", "Juguetes Y Actividades", "Muebles Para Bebe", "Seguridad Del Bebe", "Viajes Bebe", "Puericultura", "Rent A Car", "Lanzadores", "Manualidades", "Lentes De Contacto Blando", "Liquidos Contactologia", "Linea Infantil", "Ropa Dormir Hombre", "Ropa Dormir Nina", "Ropa Dormir Nino", "Calcetines Escolar", "Interior Hombre", "Interior Nina", "Interior Nino", "Todo A", "Calcetines Hombre", "Calcetines Nino", "Calcetines Nina", "Bolsas Multiuso", "Bottoms Mujer", "Wipes", "Cosmeticos", "Como Visto En Tv", "Vestidos", "Outwear", "Top", "Bottom", "Polerones Y Sweaters", "Accesorios De Vestir", "Accesorios Mujer", "Otros", "Movilidad Urbana", "Otros"]
